services:
  - type: web
    name: braniac-backend-main
    env: node
    region: oregon
    branch: main
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: braniac-backend-master
    env: node
    region: oregon
    branch: master
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

  - type: static
    name: braniac-frontend
    type: web
    runtime: static
    branch: main
    plan: free
    buildCommand: echo "No build required"
    staticPublishPath: frontend
    autoDeploy: true
